#!/usr/bin/env bash

if [ ! -f go.mod ]; then
    go mod init fdsa.ltd/ng
fi

# OLDGOPATH="$GOPATH"
# export GOPATH=`pwd`

# gofmt -w src
set GOOS=linux
set GOARCH=amd64
go build -o bin/ng fdsa.ltd/ng/src

set GOOS=windows
set GOARCH=amd64
go build -o bin/ng.exe fdsa.ltd/ng/src

# rm -f go.mod
# rm -f go.sum
echo 'finished'